#!/bin/sh

set -e

version=2.5.0
icecastversion=icecast-$version
icecastsrc=$icecastversion.tar.gz
checksum=b1402712a79734d4720c8fe15fd9fb10
destdir=/tmp/install-icecast-$version

package() {
fpm -s dir -t deb -n icecast250 -v $version -C root \
  --after-install  icecast2.postinst \
  --before-install icecast2.preinst \
  --after-remove icecast2.postrm \
  -p icecast-VERSION_ARCH.deb \
  -d "libvorbis0a" \
  -d "libogg0" \
  -d "curl" \
  -d "libxml2" \
  -d "libxslt1.1" \
  -d "libtheora0" \
  -d "libvorbisenc2" \
  -d "vorbis-tools" \
  -d "speex" \
   .
}

sudo apt-get -y install libtheora-dev libogg-dev libxslt-dev libxml2-dev libssl-dev cdbs dh-buildinfo automake1.10 libcurl4-gnutls-dev devscripts libvorbis-dev

function from_tar() {

if [ ! -f $icecastsrc ]; then
    wget -q http://downloads.xiph.org/releases/icecast/$icecastsrc
fi

if [ "$(md5sum $icecastsrc | cut -b1-32)" != "$checksum" ]; then
  echo "Checksum mismatch!"
  exit 1
fi

rm -rf $destdir

echo "Unpacking $icecastsrc"
tar -xvzf $icecastsrc
cd $icecastversion
./configure && make
cd ..
mkdir -p root/usr/local/bin

cp icecast-${version}/src/icecast root/usr/local/bin/icecast2
}

function from_source() {

git clone --recursive https://git.xiph.org/icecast-server.git
cd icecast-server
./autogen.sh
make
cd ..
mkdir -p root/usr/local/bin
cp icecast-server/src/icecast root/usr/local/bin/icecast2

}

from_source

gem list -i fpm || sudo gem install fpm

package
